# Generated by Django 5.0.4 on 2025-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('Primary', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=30),
        ),
    ]
