# Generated by Django 2.2.14 on 2020-09-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200920_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='amount',
            new_name='percentage',
        ),
    ]
