# Generated by Django 5.0.4 on 2025-03-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FS', 'Full Sheet Frame'), ('FM', 'Full Metal Frame'), ('3P', 'Without Frame'), ('SP', 'Half Frame')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=30),
        ),
    ]
