# Generated by Django 2.2.14 on 2020-10-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200928_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.TextField(default='This is a description of the product.'),
        ),
        migrations.AddField(
            model_name='item',
            name='fview',
            field=models.ImageField(blank=True, null=True, upload_to='media/Item/'),
        ),
        migrations.AddField(
            model_name='item',
            name='sview',
            field=models.ImageField(blank=True, null=True, upload_to='media/Item/'),
        ),
    ]
