# Generated by Django 2.2.14 on 2020-10-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201015_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeLenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_type', models.CharField(blank=True, choices=[('Z', 'Zero Power'), ('B', 'Bifocal Power'), ('S', 'Single Power')], max_length=1, null=True)),
                ('lenses_type', models.CharField(blank=True, choices=[('HC', 'Regular'), ('KT', 'Bifocal'), ('AR', 'Anti-Glare'), ('BB', 'Blue Blocker')], max_length=1, null=True)),
                ('image', models.ImageField(upload_to='user_prescription/')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='lenses_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='lenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EyeLenses'),
        ),
    ]
