# Generated by Django 2.2.14 on 2020-10-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201016_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyelenses',
            name='lenses_type',
            field=models.CharField(blank=True, choices=[('HC', 'Regular'), ('KT', 'Bifocal'), ('AR', 'Anti-Glare'), ('BB', 'Blue Blocker')], max_length=2, null=True),
        ),
    ]
