# Generated by Django 2.2.14 on 2020-10-15 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_eyelenses_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyelenses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
