# Generated by Django 2.2.14 on 2020-10-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201016_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyelenses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_prescription/'),
        ),
    ]
