# Generated by Django 2.2.14 on 2020-10-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201016_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eyelenses',
            old_name='image',
            new_name='prescription_image',
        ),
    ]
