# Generated by Django 2.2.14 on 2020-10-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyelenses',
            name='lenses_type',
            field=models.CharField(blank=True, choices=[('HC', 'Regular'), ('AR', 'Anti-Glare'), ('BB', 'Blue Blocker')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FS', 'Full Sheet Frame'), ('FM', 'Full Metal Frame'), ('3P', 'Without Frame'), ('SP', 'Half Frame')], max_length=2),
        ),
    ]
