# Generated by Django 2.2.14 on 2020-10-18 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201018_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyelenses',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
