# Generated by Django 2.2.14 on 2020-10-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201018_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_confirmed',
            new_name='failed_confirm',
        ),
    ]
