# Generated by Django 2.2.14 on 2020-10-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201018_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remark_for_failure',
            field=models.TextField(default='Please Contact to the store.'),
        ),
    ]
