# Generated by Django 2.2.14 on 2025-02-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_remark_for_failure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
