# Generated by Django 2.2.14 on 2025-02-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_book_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='Phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
