# Generated by Django 5.1.6 on 2025-03-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_customuser_delete_appointment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
