# Generated by Django 5.1.6 on 2025-03-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('FS', 'Full Sheet Frame'), ('FM', 'Full Metal Frame'), ('3P', 'Without Frame'), ('SP', 'Half Frame')], max_length=2)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1)),
                ('slug', models.SlugField()),
                ('description', models.TextField(default='This is a description of the product.')),
                ('features', models.TextField(default='This is a description of the product.')),
                ('fview', models.ImageField(blank=True, null=True, upload_to='media/Item/')),
                ('sview', models.ImageField(blank=True, null=True, upload_to='media/Item/')),
            ],
        ),
    ]
