# Generated by Django 5.0.4 on 2025-03-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_alter_item_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
